version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: crate-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: crate
      POSTGRES_PASSWORD: crate
      POSTGRES_DB: crate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
